<?php

namespace chippyash\Test\Zend\Acl\Xml\Exceptions;

use chippyash\Zend\Acl\Xml\Exceptions\AclBuilderException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 14:31:57.
 */
class AclBuilderExceptionTest extends \PHPUnit_Framework_TestCase
{
    public function testAclBuilderExceptionExtendsPHPException()
    {
        $e = new AclBuilderException();
        $this->assertInstanceOf('Exception', $e);
    }
}
