<?php

namespace chippyash\Test\Zend\Acl\Xml;

use chippyash\Zend\Acl\Xml\AbstractAclItemBuilder;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 10:52:54.
 */
class AbstractAclItemBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractAclItemBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $dom = $this->getMock('DOMDocument');
        $acl = $this->getMock('Zend\Permissions\Acl\Acl');
        $this->object = $this->getMockForAbstractClass(
                'chippyash\Zend\Acl\Xml\AbstractAclItemBuilder',
                [$dom, $acl],'',true);
    }

    public function testBuildItemReturnsBoolean()
    {
        $this->object->expects($this->once())
                ->method('buildItem')
                ->will($this->returnValue(true));
        
        $this->assertTrue($this->object->build());
        $results = $this->object->getResult();
        $this->assertTrue($results['result']);
    }
    
}
