<?php

namespace Chippyash\Test\Zend\Acl\Xml;

use Chippyash\Zend\Acl\Xml\AclDirector;
use Chippyash\Type\String\StringType;

require_once __DIR__ . '/Stubs/TestResourceStub.php';
require_once __DIR__ . '/Stubs/TestRoleStub.php';
require_once __DIR__ . '/Stubs/TestAssertionStub.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 10:52:53.
 */
class AclDirectorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AclDirector
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AclDirector(new StringType(__DIR__ . '/fixtures/test.xml'));
    }

    public function testDirectorBuildWillReturnZendAcl()
    {
        $this->assertInstanceOf('Zend\Permissions\Acl\Acl', $this->object->build());
    }
}
