<?php

namespace chippyash\Test\Zend\Acl\Xml;

use chippyash\Zend\Acl\Xml\AclRenderer;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-21 at 10:57:46.
 */
class AclRendererTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AclRenderer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AclRenderer();
    }

    public function testRenderWillReturnAclItem()
    {
        $builder = $this->getMock('chippyash\BuilderPattern\BuilderInterface');
        $builder->expects($this->once())
                ->method('getResult')
                ->will($this->returnValue(['acl'=>'foo']));
        $this->assertEquals('foo', $this->object->render($builder));
    }

}
